version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql:${MYSQL_VERSION}
    restart: always
    ports:
      - ${EXPOSE}:3306
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./dumps:/dumps
      - ./lib:/var/lib/mysql
